# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: EE4802_IE4213_Assignment 2
author: Chen Shenghao

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Information about where the book exists on the web
repository:
  url: https://github.com/shenghaoc/ee4802-assignment2  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - html_image

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
